name: CICD

on:
  push:
    branches: [ "MAIN" ]
  pull_request:
    branches: [ "MAIN" ]

jobs:
  build:

    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: Trivy FS Scan
      run: trivy fs --format table -o fs.html .

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Image
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: |
          docker push owaiskhan84/prodtaskmaster:latest
          
    - name: Kubectl Action
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG_PROD }}
    - run: |
          kubectl apply -f deployment-service.yml
